import {
  DEVICE_KNOWLEDGE_MODULE_SCHEMA_VERSION,
  type CommandPattern,
  type DeviceKnowledgeModuleData,
  type DocIndexEntry,
  type FailureHint,
  type PromptFragment,
} from '@device-knowledge/core';

const SOURCE_RETRIEVED_AT = '2026-05-28';

const RK_SCOPE = {
  platforms: [
    'rock-5b',
    'rock-5-itx',
    'orange-pi-5-plus',
    'firefly-roc-rk3588s-pc',
    'rockchip-generic',
  ],
  boards: [
    'radxa-rock-5b',
    'radxa-rock-5-itx',
    'orange-pi-5-plus',
    'firefly-roc-rk3588s-pc',
  ],
  socs: ['rk3588', 'rk3588s'],
};

const rkEcosystemText = [
  '## Rockchip RK 生态（提要）',
  '- 常见开发板包括 Radxa ROCK 5 系列、Orange Pi 5 系列、Firefly ROC-RK3588S-PC 等。',
  '- RK3588/RK3588S NPU 标称 6 TOPS；模型部署通常使用 RKNN Toolkit 2 转换为 `.rknn`，板端使用 `librknnrt` / `rknn_toolkit_lite2` 推理。',
  '- 不要套用 RDK BPU/TROS、Jetson CUDA/TensorRT 或 Raspberry Pi HAT 的路径；先确认系统镜像、内核、NPU runtime 和 rknn-toolkit2 版本是否匹配。',
].join('\n');

const promptFragments: PromptFragment[] = [
  {
    id: 'rk-ecosystem-v1',
    section: 'ecosystem',
    tier: 'all',
    mode: 'all',
    priority: 40,
    content: [
      '## Rockchip RK 设备上下文（知识模块）',
      '- 典型 RK3588/RK3588S 板卡是通用 Linux SBC；AI 推理优先走 RKNN `.rknn`，不是 RDK `.bin`、Jetson TensorRT engine 或 Raspberry Pi Hailo HEF。',
      '- 诊断先用通用只读命令：`uname -a`、`cat /etc/os-release`、`cat /proc/device-tree/model`、`lscpu`、`lsusb`、`dmesg | grep -i rknpu`。',
      '- NPU 可用性取决于镜像内核驱动、`librknnrt` 与模型转换工具版本；遇到 RKNN 报错先核对 runtime/toolkit 版本，不要默认是模型本身错误。',
    ].join('\n'),
    source: {
      type: 'official-doc',
      url: 'https://docs.radxa.com/en/rock5/rock5b',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    tags: ['rockchip', 'rk3588', 'rknn', 'npu'],
    language: 'zh-CN',
    status: 'active',
    confidence: 'high',
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'Rockchip RK ecosystem prompt',
  },
];

const rk3588BaseProfile = {
  soc: 'Rockchip RK3588',
  computeUnit: 'NPU (RKNN) / Mali-G610 GPU / CPU',
  computeTops: 6,
  cpu: '4-core Cortex-A76 + 4-core Cortex-A55',
  modelFormat: 'rknn',
  diagnosticCommand: 'cat /proc/device-tree/model 2>/dev/null; uname -a; dmesg | grep -i rknpu | tail -20',
  runtimeBasePath: '/usr/lib',
  systemPython: '/usr/bin/python3',
  inferLibPackage: 'librknnrt / rknn_toolkit_lite2',
  limitations: [
    'RKNN models are tied to RKNN Toolkit 2 and board-side runtime versions; mismatches can fail at load time.',
    'Vendor images vary by board maker; verify kernel, device tree, and NPU runtime before assuming NPU availability.',
    'CUDA/TensorRT, RDK BPU `.bin`, and Raspberry Pi Hailo/IMX500 artifacts are not compatible with RK NPU.',
  ],
  docBaseUrl: 'https://docs.radxa.com/en/rock5/rock5b',
  capabilityNotes: [
    'RK3588/RK3588S NPU 标称 6 TOPS；推理模型通常为 `.rknn`。',
    '模型转换一般在 x86/Linux 主机完成，板端只负责运行 runtime。',
    '优先使用板厂镜像文档与 Rockchip RKNN Toolkit 2 示例核对 runtime 版本。',
  ],
  sourceUrls: [
    'https://docs.radxa.com/en/rock5/rock5b/getting-started/introduction',
    'https://docs.radxa.com/en/rock5/rock5itx/getting-started/introduction',
    'https://wiki.t-firefly.com/en/ROC-RK3588S-PC/',
    'http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html',
    'https://github.com/airockchip/rknn-toolkit2',
  ],
  lastReviewedAt: SOURCE_RETRIEVED_AT,
};

const rkProfiles = {
  'rock-5b': {
    ...rk3588BaseProfile,
    platform: 'rock-5b',
    displayName: 'Radxa ROCK 5B',
    ramGb: 8,
    ramOptionsGb: [4, 8, 16, 32],
    storageSpec: 'microSD / eMMC module / M.2 NVMe (board support depends on carrier and image)',
    powerSpec: 'USB-C PD / DC input, size for peripherals and NVMe load',
    detectionPatterns: ['rock 5b', 'rock-5b', 'radxa rock 5', 'rk3588'],
    recommendedUseCases: ['RKNN NPU demos', 'edge vision', 'robotics Linux host', 'media pipelines'],
  },
  'rock-5-itx': {
    ...rk3588BaseProfile,
    platform: 'rock-5-itx',
    displayName: 'Radxa ROCK 5 ITX',
    ramGb: 16,
    ramOptionsGb: [4, 8, 16, 32],
    storageSpec: 'eMMC / M.2 NVMe / SATA depending on board configuration',
    powerSpec: 'ATX-style or DC input depending on kit; size for drives and accelerator load',
    detectionPatterns: ['rock 5 itx', 'rock-5-itx', 'radxa rock 5 itx', 'rk3588'],
    recommendedUseCases: ['RKNN NPU demos', 'edge server', 'multi-storage robotics host'],
  },
  'orange-pi-5-plus': {
    ...rk3588BaseProfile,
    platform: 'orange-pi-5-plus',
    displayName: 'Orange Pi 5 Plus',
    ramGb: 16,
    ramOptionsGb: [4, 8, 16, 32],
    docBaseUrl: 'http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html',
    storageSpec: 'microSD / eMMC / M.2 NVMe depending on SKU and carrier setup',
    powerSpec: 'USB-C power input; size for peripherals and NVMe load',
    detectionPatterns: ['orange pi 5 plus', 'orangepi 5 plus', 'rk3588'],
    recommendedUseCases: ['RKNN NPU demos', 'edge vision', 'media pipelines'],
  },
  'firefly-roc-rk3588s-pc': {
    ...rk3588BaseProfile,
    platform: 'firefly-roc-rk3588s-pc',
    displayName: 'Firefly ROC-RK3588S-PC',
    soc: 'Rockchip RK3588S',
    ramGb: 8,
    ramOptionsGb: [4, 8, 16, 32],
    docBaseUrl: 'https://wiki.t-firefly.com/en/ROC-RK3588S-PC/',
    storageSpec: 'microSD / eMMC module, board-specific expansion options',
    powerSpec: 'DC input; size for workload and peripherals',
    detectionPatterns: ['roc-rk3588s-pc', 'firefly rk3588s', 'rk3588s'],
    recommendedUseCases: ['RKNN NPU demos', 'edge vision', 'embedded Linux development'],
  },
};

const docs: DocIndexEntry[] = [
  {
    id: 'rk-doc-radxa-rock5b',
    title: 'Radxa ROCK 5B Documentation',
    url: 'https://docs.radxa.com/en/rock5/rock5b/getting-started/introduction',
    sourceUrl: 'https://docs.radxa.com/en/rock5/rock5b/getting-started/introduction',
    sourceType: 'official-doc',
    section: 'official',
    tags: ['rockchip', 'rk3588', 'radxa', 'rock-5b'],
    language: 'en',
    status: 'active',
    confidence: 'high',
    priority: 70,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'Radxa ROCK 5B Documentation',
    source: {
      type: 'official-doc',
      url: 'https://docs.radxa.com/en/rock5/rock5b/getting-started/introduction',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    chunkPolicy: {
      strategy: 'heading',
      maxTokens: 800,
      overlapTokens: 120,
    },
    metadataForEmbedding: ['title', 'section', 'tags', 'platforms'],
    metadataForPrompt: ['title', 'url', 'section', 'lastReviewedAt'],
  },
  {
    id: 'rk-doc-radxa-rock5itx',
    title: 'Radxa ROCK 5 ITX Documentation',
    url: 'https://docs.radxa.com/en/rock5/rock5itx/getting-started/introduction',
    sourceUrl: 'https://docs.radxa.com/en/rock5/rock5itx/getting-started/introduction',
    sourceType: 'official-doc',
    section: 'official',
    tags: ['rockchip', 'rk3588', 'radxa', 'rock-5-itx'],
    language: 'en',
    status: 'active',
    confidence: 'high',
    priority: 69,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'Radxa ROCK 5 ITX Documentation',
    source: {
      type: 'official-doc',
      url: 'https://docs.radxa.com/en/rock5/rock5itx/getting-started/introduction',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    chunkPolicy: {
      strategy: 'heading',
      maxTokens: 800,
      overlapTokens: 120,
    },
    metadataForEmbedding: ['title', 'section', 'tags', 'platforms'],
    metadataForPrompt: ['title', 'url', 'section', 'lastReviewedAt'],
  },
  {
    id: 'rk-doc-rknn-toolkit2',
    title: 'Rockchip RKNN Toolkit 2',
    url: 'https://github.com/airockchip/rknn-toolkit2',
    sourceUrl: 'https://github.com/airockchip/rknn-toolkit2',
    sourceType: 'github',
    section: 'toolchain',
    tags: ['rockchip', 'rknn', 'toolkit', 'npu'],
    language: 'en',
    status: 'active',
    confidence: 'high',
    priority: 68,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'Rockchip RKNN Toolkit 2',
    source: {
      type: 'github',
      url: 'https://github.com/airockchip/rknn-toolkit2',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    chunkPolicy: {
      strategy: 'heading',
      maxTokens: 800,
      overlapTokens: 120,
    },
    metadataForEmbedding: ['title', 'section', 'tags', 'platforms'],
    metadataForPrompt: ['title', 'url', 'section', 'lastReviewedAt'],
  },
  {
    id: 'rk-doc-orange-pi-5-plus',
    title: 'Orange Pi 5 Plus Product Page',
    url: 'http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html',
    sourceUrl: 'http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html',
    sourceType: 'official-doc',
    section: 'official',
    tags: ['rockchip', 'rk3588', 'orange-pi', 'orange-pi-5-plus'],
    language: 'en',
    status: 'active',
    confidence: 'medium',
    priority: 62,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'Orange Pi 5 Plus Product Page',
    source: {
      type: 'official-doc',
      url: 'http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    chunkPolicy: {
      strategy: 'heading',
      maxTokens: 800,
      overlapTokens: 120,
    },
    metadataForEmbedding: ['title', 'section', 'tags', 'platforms'],
    metadataForPrompt: ['title', 'url', 'section', 'lastReviewedAt'],
  },
  {
    id: 'rk-doc-firefly-rk3588s',
    title: 'Firefly ROC-RK3588S-PC Wiki',
    url: 'https://wiki.t-firefly.com/en/ROC-RK3588S-PC/',
    sourceUrl: 'https://wiki.t-firefly.com/en/ROC-RK3588S-PC/',
    sourceType: 'official-doc',
    section: 'official',
    tags: ['rockchip', 'rk3588s', 'firefly'],
    language: 'en',
    status: 'active',
    confidence: 'medium',
    priority: 60,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'Firefly ROC-RK3588S-PC Wiki',
    source: {
      type: 'official-doc',
      url: 'https://wiki.t-firefly.com/en/ROC-RK3588S-PC/',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    chunkPolicy: {
      strategy: 'heading',
      maxTokens: 800,
      overlapTokens: 120,
    },
    metadataForEmbedding: ['title', 'section', 'tags', 'platforms'],
    metadataForPrompt: ['title', 'url', 'section', 'lastReviewedAt'],
  },
];

const commandPatterns: CommandPattern[] = [
  {
    id: 'rk-command-rknpu-dmesg',
    pattern: { source: 'dmesg\\s*\\|\\s*grep\\s+(-i\\s+)?rknpu', flags: 'i' },
    category: 'diagnostics',
    description: 'Inspect Rockchip NPU driver/runtime messages',
    riskLevel: 'safe',
    source: {
      type: 'github',
      url: 'https://github.com/airockchip/rknn-toolkit2',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    tags: ['rockchip', 'rknn', 'diagnostics'],
    status: 'active',
    confidence: 'high',
    priority: 55,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'RKNN Toolkit diagnostics',
  },
  {
    id: 'rk-command-rknn-install',
    pattern: { source: 'pip\\s+install\\s+.*rknn|rknn[-_]toolkit', flags: 'i' },
    category: 'toolchain',
    description: 'RKNN Toolkit installation or runtime package setup',
    riskLevel: 'moderate',
    source: {
      type: 'github',
      url: 'https://github.com/airockchip/rknn-toolkit2',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    tags: ['rockchip', 'rknn', 'pip'],
    status: 'active',
    confidence: 'high',
    priority: 52,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'RKNN Toolkit install',
  },
];

const failureHints: FailureHint[] = [
  {
    id: 'rk-failure-rknn-runtime-mismatch',
    errorPattern: { source: 'RKNN.*(version|mismatch|init runtime|load model|invalid model)|librknnrt', flags: 'i' },
    suggestion: 'RKNN runtime/toolkit mismatch is common. Check board-side `librknnrt` / `rknn_toolkit_lite2` version, then rebuild the `.rknn` model with the matching RKNN Toolkit 2 release.',
    docUrl: 'https://github.com/airockchip/rknn-toolkit2',
    source: {
      type: 'github',
      url: 'https://github.com/airockchip/rknn-toolkit2',
      retrievedAt: SOURCE_RETRIEVED_AT,
    },
    scope: RK_SCOPE,
    tags: ['rockchip', 'rknn', 'runtime'],
    status: 'active',
    confidence: 'high',
    priority: 60,
    lastReviewedAt: SOURCE_RETRIEVED_AT,
    citationLabel: 'RKNN runtime mismatch hint',
  },
];

export const rkKnowledgeModuleData: DeviceKnowledgeModuleData & { ecosystemText: string } = {
  manifest: {
    schemaVersion: DEVICE_KNOWLEDGE_MODULE_SCHEMA_VERSION,
    id: 'rockchip-sbc',
    name: 'Rockchip RK SBC',
    version: '0.1.0',
    origin: 'official',
    family: 'rockchip',
    priority: 40,
    compatibility: {
      dmossKnowledgeModule: '^0.3.1',
      minRdkStudio: '1.2.0',
    },
  },
  profiles: rkProfiles,
  docs,
  promptFragments,
  commandPatterns,
  failureHints,
  skills: [],
  ecosystemText: rkEcosystemText,
};

export function getRkResearchSeeds(): string[] {
  return [
    'https://docs.radxa.com/en/rock5/rock5b/getting-started/introduction',
    'https://docs.radxa.com/en/rock5/rock5itx/getting-started/introduction',
    'https://github.com/airockchip/rknn-toolkit2',
    'https://wiki.t-firefly.com/en/ROC-RK3588S-PC/',
    'http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html',
  ];
}
